### ISSUE TITLE
No module-info.java?

### ISSUE THREAD

**Issue by brainstorm** [kocakosm/jblake2#2]
Cannot use it w/ JDK>=9 and projects that are modularised :_/

**Comment by kocakosm** [comment]
This library is fully compatible with Java 9+ and can be perfectly used in a modular application (JARs on the module path are turned into [automatic modules](https://dev.java/learn/modules/automatic-module/)). 

**Note** : as specified in the project's `README.md`, the module name is `org.kocakosm.jblake2`.

**Comment by brainstorm** [comment]
You should read this: https://dev.java/learn/modules/intro/

No worries, I'll use another library that includes a `module-info.java` and exports/requires modules the proper way.
